# The URL the site will be built for
base_url = "https://www.comaps.app"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "CoMaps"
description = "Free offline maps app for travellers, tourists, hikers, and cyclists based on OpenStreetMap data. Privacy and community focused, and open-source forever ♥️"
author = "hello@comaps.app"
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]


taxonomies = [
    # {name = "faq", feed = false},
    {name = "support", feed = false},
    {name = "category", paginate_by = 50, feed = false}
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
#default_language = "en"



# [search]
# Whether to include the title of the page/section in the index
# include_title = true
# Whether to include the description of the page/section in the index
# include_description = false
# Whether to include the RFC3339 datetime of the page in the search index
# include_date = false
# Whether to include the path of the page/section in the index (the permalink is always included)
# include_path = true
# Whether to include the rendered content of the page/section in the index
# include_content = true
# At which code point to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100

# Whether to produce the search index as a javascript file or as a JSON file
# Accepted values:
# - "elasticlunr_javascript", "elasticlunr_json"
# - "fuse_javascript", "fuse_json"
# index_format = "elasticlunr_json"

# ignored_content = [".DS_Store"]

[link_checker]
internal_level = "warn"

[markdown]
external_links_target_blank = true

# Allows to have localized URLs.
[slugify]
paths = "safe"
taxonomies = "on"

# [extra]
# stripe = "https://donate.comaps.app/"

[[extra.social]]
title = "mastodon"
icon = "mastodon.svg"
link = "https://floss.social/@CoMaps"

[[extra.social]]
title = "matrix"
icon = "matrix.svg"
link = "https://matrix.to/#/%23comaps:matrix.org"

[[extra.social]]
title = "Bluesky"
icon = "bluesky.svg"
link = "https://bsky.app/profile/comaps.app"

[[extra.social]]
title = "telegram"
icon = "telegram.svg"
link = "https://t.me/CoMapsApp"

[[extra.social]]
title = "Lemmy"
icon = "lemmy.svg"
link = "https://sopuli.xyz/c/CoMaps"

[[extra.social]]
title = "Instagram"
icon = "insta.svg"
link = "https://www.instagram.com/comapscommunity/"

[[extra.social]]
title = "facebook"
icon = "fb.svg"
link = "https://www.facebook.com/CoMapsCommunity/"

[[extra.social]]
title = "linkedin"
icon = "linkedin.svg"
link = "https://www.linkedin.com/company/comaps-community/"

[[extra.social]]
title = "reddit"
icon = "reddit.svg"
link = "https://www.reddit.com/r/CoMaps/"

[[extra.social]]
title = "threads"
icon = "threads.svg"
link = "https://www.threads.com/@comapscommunity"

[[extra.social]]
title = "tiktok"
icon = "tiktok.svg"
link = "https://www.tiktok.com/@comapscommunity"

# [[extra.social]]
# title = "youtube"
# icon = "youtube.svg"
# link = ""

# [[extra.social]]
# title = "x"
# icon = "x.svg"
# link = ""
# class= "icon-x"

# [[extra.social]]
# title = "github"
# icon = "github-circle.svg"
# link = ""
# class= "icon-github"

[[extra.social]]
title = "email"
icon = "email.svg"
link = "mailto:hello@comaps.app"




# Default English translation
[translations]
language = "English"
const_lang = "Language"
button-download = "Download"
faq_content = "CoMaps - F.A.Q."
# Navigation Menu
menu_home = "Home"
menu_news = "News"
menu_community = "Community"
menu_donate = "Donate"
menu_help = "Help"
menu_about_us = "About Us"
menu_source_code = "Source Code"
menu_api = "API"
# News
all_title = "All"
releases_title = "Releases"
more_title = "More"
# Support
how_can_help = "How can we help?"
search_placeholder = "Describe the issue"
search_placeholder_simple = "Search"
# Social
social_title = "Connect with Us"
# Get Involved / Donate
inv_title = "Get Involved"
donate-description = "The app runs on your donations, help improve it"
inv_code_title = "Contribute Code"
inv_code_text = "Build the app used by people around the world"
inv_info_title = "Add Place Info"
inv_info_text = "Add info around you, and make the maps better for everyone"


# Please sort all other translation sections and values in alphabetical order.
[languages.de]
[languages.de.translations]
language = "Deutsch"
const_lang = "Sprache"
button-download = "Download"
faq_content = "CoMaps - F.A.Q."
menu_home = "Home"
menu_news = "Neuigkeiten"
menu_community = "Community"
menu_donate = "Spenden"
menu_help = "Hilfe"
menu_about_us = "Über uns"
menu_source_code = "Quellcode"
menu_api = "API"
all_title = "Alle"
releases_title = "Releases"
more_title = "Mehr"
how_can_help = "Wie können wir helfen?"
search_placeholder = "Beschreibe das Problem"
search_placeholder_simple = "Suche"
social_title = "Bleib in Kontakt"
inv_title = "Mitmachen"
donate-description = "Die App lebt von deinen Spenden – hilf mit, sie zu verbessern"
inv_code_title = "Code beitragen"
inv_code_text = "Entwickle die weltweit genutzte App"
inv_info_title = "Ortsinformationen hinzufügen"
inv_info_text = "Füge Infos aus deiner Umgebung hinzu und verbessere die Karten für alle"
[languages.fr]
[languages.fr.translations]
language = "Anglais"
const_lang = "Langue"
button-download = "Télécharger"
faq_content = "CoMaps - F.A.Q."
menu_home = "Accueil"
menu_news = "Actualités"
menu_community = "Communauté"
menu_donate = "Faire un don"
menu_help = "Aide"
menu_about_us = "À propos de nous"
menu_source_code = "Code source"
menu_api = "API"
all_title = "Tout"
releases_title = "Versions"
more_title = "Plus"
how_can_help = "Comment pouvons-nous vous aider ?"
search_placeholder = "Décrivez le problème"
search_placeholder_simple = "Rechercher"
social_title = "Rentrez en contact avec nous"
inv_title = "Impliquez-vous"
donate-description = "L'application dépend de vos dons, aidez à l'améliorer"
inv_code_title = "Contribuez au code"
inv_code_text = "Construisez l'application utilisée par les gens autour du monde"
inv_info_title = "Ajoutez des infos sur les lieux"
inv_info_text = "Ajoutez des infos autour de vous, et rendez les cartes meilleures pour tout le monde"
[languages.it]
[languages.it.translations]
language = "Italiano"
const_lang = "Lingua"
button-download = "Scarica"
faq_content = "CoMaps - F.A.Q."
menu_home = "Home"
menu_news = "Notizie"
menu_community = "Comunità"
menu_donate = "Dona"
menu_help = "Aiuto"
menu_about_us = "Chi siamo"
menu_source_code = "Codice sorgente"
menu_api = "API"
all_title = "Tutto"
releases_title = "Versioni"
more_title = "Di più"
how_can_help = "Come possiamo aiutarti?"
search_placeholder = "Descrivi il problema"
search_placeholder_simple = "Cerca"
social_title = "Contattaci"
inv_title = "Partecipa"
donate-description = "L'app dipende dai tuoi doni, contribuisci a migliorarla"
inv_code_title = "Contribuisci al codice"
inv_code_text = "Costruisci l'applicazione utilizzata da persone in tutto il mondo"
inv_info_title = "Aggiungi delle informazioni sui posti"
inv_info_text = "Aggiungi delle informazioni intorno a te, e rendi le mappe migliori per tutti"
[languages.cs]
[languages.cs.translations]
language = "Čeština"
const_lang = "Jazyk"
button-download = "Stáhnout"
faq_content = "CoMaps – Časté dotazy"
menu_home = "Domů"
menu_news = "Novinky"
menu_community = "Komunita"
menu_donate = "Darovat"
menu_help = "Nápověda"
menu_about_us = "O nás"
menu_source_code = "Zdrojový kód"
menu_api = "API"
all_title = "Vše"
releases_title = "Vydání"
more_title = "Více"
how_can_help = "Jak vám můžeme pomoci?"
search_placeholder = "Popište problém"
search_placeholder_simple = "Hledat"
social_title = "Spojte se s námi"
inv_title = "Zapojte se"
donate-description = "Tuto aplikaci pohání vaše dary, pomozte ji vylepšit"
inv_code_title = "Přispějte kódem"
inv_code_text = "Vytvářejte aplikaci používanou lidmi po celém světě"
inv_info_title = "Přidávejte místa"
inv_info_text = "Přidávejte informace kolem sebe a zlepšete tím mapy pro všechny ostatní"
[languages.pt.translations]
language = "Português"
const_lang = "Language"
button-download = "Faça o Download do CoMaps"
faq_content = "CoMaps - F.A.Q."
menu_home = "Início"
menu_news = "Notícias"
menu_community = "Comunidade"
menu_donate = "Donativos"
menu_help = "Help"
menu_about_us = "Sobre nós"
menu_source_code = "Source Code"
menu_api = "API"
all_title = "All"
releases_title = "Notícias e Lançamentos"
more_title = "More"
how_can_help = "How can we help?"
search_placeholder = "Describe the issue"
search_placeholder_simple = "Search"
social_title = "Connect with Us"
inv_title = "Get Involved"
donate-description = "Esta aplicação depende dos vossos donativos, ajude a torná-la melhor"
inv_code_title = "Contribute Code"
inv_code_text = "Build the app used by people around the world"
inv_info_title = "**Adicionar** Informação sobre o lugar"
inv_info_text = "Add info around you, and make the maps better for everyone"
[languages.pt-BR.translations]
language = "Português (Brazil)"
const_lang = "Language"
button-download = "Baixar CoMaps"
faq_content = "CoMaps - F.A.Q."
menu_home = "Home"
menu_news = "News"
menu_community = "Comunidade"
menu_donate = "Doar"
menu_help = "Help"
menu_about_us = "Sobre Nós"
menu_source_code = "Source Code"
menu_api = "API"
all_title = "All"
releases_title = "Notícias e Lançamentos"
more_title = "More"
how_can_help = "How can we help?"
search_placeholder = "Describe the issue"
search_placeholder_simple = "Search"
social_title = "Connect with Us"
inv_title = "Get Involved"
donate-description = "O aplicativo funciona com suas doações, ajude a melhorá-lo"
inv_code_title = "Contribute Code"
inv_code_text = "Build the app used by people around the world"
inv_info_title = "**Adicionar** Informações de Locais"
inv_info_text = "Add info around you, and make maps better for everyone"
[languages.es.translations]
language = "Español"
const_lang = "Idioma"
button-download = "Descargar"
faq_content = "CoMaps - Preguntas frecuentes"
menu_home = "Inicio"
menu_news = "Noticias"
menu_community = "Comunidad"
menu_donate = "Donar"
menu_help = "Ayuda"
menu_about_us = "Acerca de"
menu_source_code = "Código fuente"
menu_api = "API"
all_title = "Todo"
releases_title = "Lanzamientos"
more_title = "Más"
how_can_help = "¿Cómo te podemos ayudar?"
search_placeholder = "Describe la incidencia"
search_placeholder_simple = "Buscar"
social_title = "Conecta con nosotros"
inv_title = "Involúcrate"
donate-description = "La aplicación funciona con tus donaciones. Ayuda a mejorarla"
inv_code_title = "Contribuye al código"
inv_code_text = "Construye la aplicación utilizada por gente de todo el mundo"
inv_info_title = "Añade información de lugar"
inv_info_text = "Añade información cerca de ti, y haz que los mapas sean mejores para todos"
[languages.hu.translations]
language = "Magyar"
const_lang = "Language"
button-download = "Download"
faq_content = "CoMaps - F.A.Q."
menu_home = "Home"
menu_news = "News"
menu_community = "Community"
menu_donate = "Donate"
menu_help = "Help"
menu_about_us = "About Us"
menu_source_code = "Source Code"
menu_api = "API"
all_title = "All"
releases_title = "Releases"
more_title = "More"
how_can_help = "How can we help?"
search_placeholder = "Describe the issue"
search_placeholder_simple = "Search"
social_title = "Connect with Us"
inv_title = "Get Involved"
donate-description = "The app runs on your donations, help improve it"
inv_code_title = "Contribute Code"
inv_code_text = "Build the app used by people around the world"
inv_info_title = "Add Place Info"
inv_info_text = "Add info around you, and make maps better for everyone"
[languages.uk.translations]
language = "Українська"
const_lang = "Language"
button-download = "Download"
faq_content = "CoMaps - F.A.Q."
menu_home = "Home"
menu_news = "News"
menu_community = "Спільнота"
menu_donate = "Пожертвувати"
menu_help = "Help"
menu_about_us = "About Us"
menu_source_code = "Source Code"
menu_api = "API"
all_title = "All"
releases_title = "Releases"
more_title = "More"
how_can_help = "How can we help?"
search_placeholder = "Describe the issue"
search_placeholder_simple = "Search"
social_title = "Connect with Us"
inv_title = "Get Involved"
donate-description = "The app runs on your donations, help improve it"
inv_code_title = "Contribute Code"
inv_code_text = "Build the app used by people around the world"
inv_info_title = "Add Place Info"
inv_info_text = "Add info around you, and make maps better for everyone"
[languages.zh-Hans.translations]
language = "中文（简体）"
const_lang = "语言"
button-download = "下载"
faq_content = "CoMaps - 常见问题"
menu_home = "主页"
menu_news = "新闻"
menu_community = "社区"
menu_donate = "捐助我们"
menu_help = "帮助"
menu_about_us = "关于我们"
menu_source_code = "源代码"
menu_api = "API"
all_title = "全部"
releases_title = "发布"
more_title = "更多"
how_can_help = "我们能帮您什么？"
search_placeholder = "描述问题"
search_placeholder_simple = "搜索"
social_title = "联系我们"
inv_title = "参与我们"
donate-description = "本应用依靠您的捐赠运行，请帮助改善它"
inv_code_title = "贡献代码"
inv_code_text = "共建世界各地都在使用的应用"
inv_info_title = "添加地点信息"
inv_info_text = "添加周围环境信息，让地图更好地为所有人服务"
[languages.ar.translations]
language = "العربية"
const_lang = "Language"
button-download = "Download"
faq_content = "CoMaps - F.A.Q."
menu_home = "Home"
menu_news = "News"
menu_community = "Community"
menu_donate = "تبرع"
menu_help = "Help"
menu_about_us = "About Us"
menu_source_code = "Source Code"
menu_api = "API"
all_title = "All"
releases_title = "التحديثات و الإصدارات"
more_title = "More"
how_can_help = "How can we help?"
search_placeholder = "Describe the issue"
search_placeholder_simple = "Search"
social_title = "Connect with Us"
inv_title = "Get Involved"
donate-description = "The app runs on your donations, help improve it"
inv_code_title = "Contribute Code"
inv_code_text = "Build the app used by people around the world"
inv_info_title = "Add Place Info"
inv_info_text = "Add info around you, and make maps better for everyone"
[languages.zh-Hant.translations]
language = "中文（繁體）"
const_lang = "語言"
button-download = "下載"
faq_content = "CoMaps - F.A.Q."
menu_home = "首頁"
menu_news = "新聞"
menu_community = "社群"
menu_donate = "捐款贊助"
menu_help = "幫助"
menu_about_us = "關於我們"
menu_source_code = "原始碼"
menu_api = "API"
all_title = "全部"
releases_title = "版本發布"
more_title = "了解更多"
how_can_help = "How can we help?"
search_placeholder = "Describe the issue"
search_placeholder_simple = "搜尋"
social_title = "Connect with Us"
inv_title = "參與我們"
donate-description = "本應用依靠您的贊助維持運作，請幫助改善它"
inv_code_title = "Contribute Code"
inv_code_text = "Build the app used by people around the world"
inv_info_title = "添加位置資訊"
inv_info_text = "Add info around you, and make the maps better for everyone"
[languages.et.translations]
language = "inglise keel"
const_lang = "Keel"
button-download = "Laadi alla"
faq_content = "CoMaps - Korduma kippuvad küsimused"
menu_home = "Avaleht"
menu_news = "Uudised"
menu_community = "Kogukond"
menu_donate = "Anneta"
menu_help = "Abiteave"
menu_about_us = "Teave meie kohta"
menu_source_code = "Lähtekood"
menu_api = "API"
all_title = "Kõik"
releases_title = "Rakenduse versioonid"
more_title = "Veel"
how_can_help = "Kuidas me saame aidata?"
search_placeholder = "Kirjelda viga"
search_placeholder_simple = "Otsi"
social_title = "Suhtle meiega"
inv_title = "Osale"
donate-description = "Selle rakenduse hooldus ja arendus põhineb vaid kasutajate toel - sinu osalemine on oluline"
inv_code_title = "Kirjuta koodi"
inv_code_text = "Aita luua kaardirakendust, mille kasutajaid leidub kõikjal maailmas"
inv_info_title = "Lisa asukohateavet"
inv_info_text = "Lisa teavet oma ümbruskonnast ja aita kõigi jaoks luua paremat kaarti"
[languages.fi.translations]
language = "Englanti"
const_lang = "Kieli"
button-download = "Lataa"
faq_content = "CoMaps - Usein kysytyt kysymykset"
menu_home = "Koti"
menu_news = "Uutiset"
menu_community = "Yhteisö"
menu_donate = "Lahjoita"
menu_help = "Ohje"
menu_about_us = "Meistä"
menu_source_code = "Lähdekoodi"
menu_api = "API"
all_title = "Kaikki"
releases_title = "Julkaisut"
more_title = "Lisää"
how_can_help = "Kuinka voimme auttaa?"
search_placeholder = "Kuvaile ongelma"
search_placeholder_simple = "Etsi"
social_title = "Ota yhteyttä"
inv_title = "Osallistu"
donate-description = "Sovelluksen ylläpito ja kehitys mahdollistetaan lahjoituksilla, auta parantamaan sitä"
inv_code_title = "Contribute Code"
inv_code_text = "Build the app used by people around the world"
inv_info_title = "Lisää paikan tiedot"
inv_info_text = "Lisää ympärilläsi olevia tietoja ja auta tekemään kartoista parempia kaikille"
