name: Publish to Codeberg Pages

env:
  ZOLA_VERSION: 0.20.0

on:
 workflow_dispatch:
 push:
   branches:
     - main
jobs:
  publish:
    runs-on: codeberg-tiny
    environment: production
    permissions:
      contents: read
      deployments: write
    name: Publish to Codeberg Pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        fetch-depth: 0

      - name: Setup Zola
        run: |
          wget -O zola.tar.gz -c https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          tar -zxvf zola.tar.gz

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Build Site
        run: | 
          ./zola build

      # Probably not needed for SFTP
      - name: Copy over README.md
        run: |
          cp README.md static/README.md

      # Probably not needed for SFTP
      - name: Stage all files
        run: |
          git add .

      # Needs work on tokens/auth in order to function
      # - name: Deploy to Codeberg Pages
      #   uses: https://itsblue.dev/actions/codeberg-pages-deploy@v1
      #   with:
      #     folder: ./public
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     force: true
      #     git_remote: https://codeberg.org/comaps/pages.git
      #     git_branch: main

      # Current primary web host (DreamHost) backed by Fastly CDN
      - name: "Deploy to DreamHost SFTP"
        uses: https://github.com/milanmk/actions-file-deployer@3cf188f493103b5f12f11221186f8fbd07f2be10
        with:
          remote-protocol: "sftp"
          remote-host: "${{secrets.SFTP_HOST}}"
          remote-user: "${{secrets.SFTP_USER}}"
          remote-password: "${{secrets.SFTP_PASS}}"
          local-path: "./public"
          remote-path: "${{vars.SFTP_PATH}}"
          sync: "full" # full for initial, delta with fetch-depth: 0 during checkout for future
