name: Publish to Codeberg Pages

env:
  ZOLA_VERSION: 0.20.0

on:
#  workflow_dispatch:
#  push:
#    branches:
#      - main
jobs:
  publish:
    runs-on: codeberg-tiny
    environment: production
    permissions:
      contents: read
      deployments: write
    name: Publish to Codeberg Pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Zola
        run: |
          wget -O zola.tar.gz -c https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          tar -zxvf zola.tar.gz

      - name: Build Site
        run: | 
          ./zola build

      - name: Copy over README.md
        run: |
          cp README.md static/README.md

      - name: Stage all files
        run: |
          git add .

      - name: Deploy to Codeberg Pages
        uses: https://itsblue.dev/actions/codeberg-pages-deploy@v1
        with:
          folder: ./public
